FROM resin/rpi-raspbian

RUN mkdir -p /usr/src/argos-presence
WORKDIR /usr/src/argos-presence

RUN apt-get update && apt-get install -y build-essential python3 python3-dev git libjpeg62 libwebp-dev libpng-dev libtiff-dev libopenjp2.7-dev libilmbase-dev libopenexr-dev libgstreamer1.0-dev libgtk-3-dev libatlas3-base
RUN python3 -m venv venv
ENV PATH="/usr/src/argos-presence/venv/bin:$PATH"
RUN pip install --upgrade pip
RUN pip install wheel

ENV READTHEDOCS=True
COPY ./ /usr/src/argos-presence/
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000
VOLUME /motion_frames
VOLUME /configs

ENV PYTHONPATH "${PYTHONPATH}:/configs"

ENTRYPOINT ["python3", "/usr/src/argos-presence/presence.py", "--ip", "0.0.0.0", "--port", "8000"]
